### PR TITLE
Updated final pester output and PesterConfiguration Object

### PR DESCRIPTION
**Pull request by belibug**
Final Pester result was showing blank because of attribute name change from Pester4 to 5. Fixed it. 
Changed the way Pester Configuration object is created. All values now lie in single hashtable which looks cleaner and easy to troubleshoot. Lesser code and slightly more readable.

### CODE REVIEW

**Comment by belibug** [comment]
AppVeyor workflow is broken, it failed, but it still marked build as complete.

**Comment by Sarafian** [comment]
Don't agree with the proposed changes. Most of it just spaces and formatting but it's fine. 
Looking at the [New-PesterConfiguration](https://pester.dev/docs/commands/New-PesterConfiguration) doc, there are two examples.
I prefer the pre-existing one (example 1) because the object is typed and then during edit it is easier. Maybe it's my background from strong typed languages that makes me biased, but anything the IDE can you for you is always appreciated and prefered. I also don't see but again, it's a matter of perspective.

> All values now lie in single hashtable which looks cleaner and easy to troubleshoot. Lesser code and slightly more readable.

Anyhow, I will reject these changes mostly because of opinion because functionally there is no difference.

You mentioned that something about a tag but I don't get it to be honest. Was there an issue already? Maybe there is something here to get.

**Comment by belibug** [comment]
Okay, I understand. On its own it doesnt add value, so its fine to keep it as is.

The bug about not showing final value, 
The last section of code , The correct properties are as below
```PowerShell
 ## Emphasis on "CommandsAnalyzedCount"
        Expression = { $_.CodeCoverage.CommandsAnalyzedCount }
    }, @{
        Name       = 'FilesAnalyzed'
        Expression = { $_.CodeCoverage.FilesAnalyzedCount }
    }, @{
        Name       = 'CommandsExecuted'
        Expression = { $_.CodeCoverage.CommandsAnalyzedCount }
    }, @{
        Name       = 'CommandsMissed'
        Expression = { $_.CodeCoverage.CommandsMissedCount }
    }
```

The old properties which are not valid anymore

```PowerShell
    $pesterResult|Select-Object @{
        Name="CommandsAnalyzed"
        Expression={$_.CodeCoverage.NumberOfCommandsAnalyzed}
    },@{
        Name="FilesAnalyzed"
        Expression={$_.CodeCoverage.NumberOfFilesAnalyzed}
    },@{
        Name="CommandsExecuted"
        Expression={$_.CodeCoverage.NumberOfCommandsExecuted}
    },@{
        Name="CommandsMissed"
        Expression={$_.CodeCoverage.NumberOfCommandsMissed}
    }
```

I can do the pull request and submit new code you can correct it on your end. Let me know.

**Comment by Sarafian** [comment]
I did an export

```text
PS /workspaces/MarkdownPS> $result

Containers            : {[+] /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.Tests.ps1, [+] /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCode.Tests.ps1, [+] /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDHeader.Tests.ps1, [+] /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDImage.Tests.ps1…}
Result                : Passed
FailedCount           : 0
FailedBlocksCount     : 0
FailedContainersCount : 0
PassedCount           : 85
SkippedCount          : 0
NotRunCount           : 0
TotalCount            : 85
Duration              : 00:00:02.3384645
Executed              : True
ExecutedAt            : 5/31/2024 3:20:13 PM
Version               : 5.5.0
PSVersion             : 7.2.19
PSBoundParameters     : {[Configuration, PesterConfiguration]}
Plugins               : 
PluginConfiguration   : 
PluginData            : 
Configuration         : PesterConfiguration
DiscoveryDuration     : 00:00:00.0528029
UserDuration          : 00:00:01.3186756
FrameworkDuration     : 00:00:00.9669860
Failed                : {}
FailedBlocks          : {}
FailedContainers      : {}
Passed                : {[+] -Style Bold, [+] -Style Italic, [+] -Style StrikeThrough, [+] -Style out of range…}
Skipped               : {}
NotRun                : {}
Tests                 : {[+] -Style Bold, [+] -Style Italic, [+] -Style StrikeThrough, [+] -Style out of range…}
CodeCoverage          : 92.09% / 75%


PS /workspaces/MarkdownPS> $result.CodeCoverage                       

CoveragePercent       : 92.090395480226
CoveragePercentTarget : 75
CoverageReport        : Covered 92.09% / 75%. 177 analyzed Commands in 13 Files.
                         Missed commands:
                         
                        File                                      Class Function               Line Command
                        ----                                      ----- --------               ---- -------
                        Modules/Import-MarkdownPS.ps1                                             1 Import-Module "$PSScriptRoot\MarkdownPS\MarkdownPS.psm1" -Force
                        Modules/MarkdownPS/MarkdownPS.psm1                                       23 $public  = @( Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -Exclude @("*.Tests.ps1"))
                        Modules/MarkdownPS/MarkdownPS.psm1                                       23 Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -Exclude @("*.Tests.ps1")
                        Modules/MarkdownPS/MarkdownPS.psm1                                       23 "*.Tests.ps1"
                        Modules/MarkdownPS/MarkdownPS.psm1                                       25 $private=@()
                        Modules/MarkdownPS/MarkdownPS.psm1                                       27 @($public + $private)
                        Modules/MarkdownPS/MarkdownPS.psm1                                       27 $public + $private
                        Modules/MarkdownPS/MarkdownPS.psm1                                       29 . $import.FullName
                        Modules/MarkdownPS/MarkdownPS.psm1                                       32 Export-ModuleMember -Function $public.BaseName
                        Modules/MarkdownPS/Public/New-MDCode.ps1        New-MDCode               72 $i++
                        Modules/MarkdownPS/Public/New-MDCode.ps1        New-MDCode               74 $prefix+=">"
                        Modules/MarkdownPS/Public/New-MDImage.ps1       New-MDImage             139 $Source+="?style=$Style"
                        Tests/Cmdlets-Helpers/Get-RandomValue.ps1       global:Get-RandomValue   18 10000 + (Get-Random -Maximum 100)
                        Tests/Cmdlets-Helpers/Get-RandomValue.ps1       global:Get-RandomValue   18 Get-Random -Maximum 100
                        
                        
                        
CommandsAnalyzedCount : 177
CommandsExecutedCount : 163
CommandsMissedCount   : 14
FilesAnalyzedCount    : 13
CommandsMissed        : {@{File=/workspaces/MarkdownPS/Src/Modules/Import-MarkdownPS.ps1; Line=1; StartLine=1; EndLine=1; StartColumn=1; EndColumn=64; Class=; Function=; Command=Import-Module "$PSScriptRoot\MarkdownPS\MarkdownPS.psm1" -Force; HitCount=0}, @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/MarkdownPS.psm1; Line=23; StartLine=23; EndLine=23; StartColumn=12; EndColumn=88; Class=; Function=; 
                        Command=$public  = @( Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -Exclude @("*.Tests.ps1")); HitCount=0}, @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/MarkdownPS.psm1; Line=23; StartLine=23; EndLine=23; StartColumn=15; EndColumn=87; Class=; Function=; Command=Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -Exclude @("*.Tests.ps1"); HitCount=0}, 
                        @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/MarkdownPS.psm1; Line=23; StartLine=23; EndLine=23; StartColumn=73; EndColumn=86; Class=; Function=; Command="*.Tests.ps1"; HitCount=0}…}
CommandsExecuted      : {@{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.ps1; Line=64; StartLine=64; EndLine=64; StartColumn=17; EndColumn=23; Class=; Function=New-MDCharacterStyle; Command=$Style; HitCount=1}, @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.ps1; Line=66; StartLine=66; EndLine=66; StartColumn=31; EndColumn=35; Class=; 
                        Function=New-MDCharacterStyle; Command=$surround="**"; HitCount=1}, @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.ps1; Line=67; StartLine=67; EndLine=67; StartColumn=33; EndColumn=36; Class=; Function=New-MDCharacterStyle; Command=$surround="*"; HitCount=1}, @{File=/workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.ps1; Line=68; 
                        StartLine=68; EndLine=68; StartColumn=40; EndColumn=44; Class=; Function=New-MDCharacterStyle; Command=$surround="~~"; HitCount=1}…}
FilesAnalyzed         : {/workspaces/MarkdownPS/Src/Modules/Import-MarkdownPS.ps1, /workspaces/MarkdownPS/Src/Modules/MarkdownPS/MarkdownPS.psm1, /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCharacterStyle.ps1, /workspaces/MarkdownPS/Src/Modules/MarkdownPS/Public/New-MDCode.ps1…}
 
```

Something have changed. Kind of my point about preference to typed code.

The CodeCoverage is currently not triggered so even if we fix this only the console output will be. But now that the codecoverage is stable, I want to look into this from the template repository and explore what might be possible with appveyor on this topic. 
I'll leave this issue for the export of the structure for convienience 

Please don't waste time on this.

**Pull request closed without merging**
